# Generated by Django 3.0.5 on 2020-04-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewiev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RewievModel',
            new_name='RewievsModel',
        ),
    ]
