# Generated by Django 3.0.5 on 2020-04-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewiev', '0002_auto_20200411_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewievsmodel',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
