# Generated by Django 3.0.5 on 2020-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartneersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя/Название')),
                ('logo', models.ImageField(blank=True, default=True, upload_to='', verbose_name='Лого')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='VeneerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discriptions', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=True, upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default=True, max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
    ]
